ci: use a single step in prepare job

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -16,7 +16,7 @@ jobs:
   prepare:
     runs-on: ubuntu-latest
     outputs:
-      version: ${{ steps.semver.outputs.version }}
+      version: ${{ steps.check.outputs.version }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -28,14 +28,6 @@ jobs:
       - id: check
         name: Check release version and commit
         run: |
-          echo "::group::Check project version matches tag"
-          RELEASE_VERSION="$(grep version pyproject.toml | cut -d'"' -f2)"
-          TAG_VERSION="$(echo "${{ github.ref_name }}" | cut -d'v' -f2)"
-          if [ "$RELEASE_VERSION" != "$TAG_VERSION" ]; then
-            echo "::error title=Version mismatch::Release version ($RELEASE_VERSION) does not match tag version ($TAG_VERSION)"
-            exit 1
-          fi
-          echo "::endgroup::"
           echo "::group::Check tag commit matches latest commit on main"
           MAIN_SHA="$(git rev-parse --verify main)"
           if [ "$MAIN_SHA" != "$GITHUB_SHA" ]; then
@@ -43,10 +35,15 @@ jobs:
             exit 1
           fi
           echo "::endgroup::"
-
-      - id: semver
-        name: Set version output
-        run: echo "version=$RELEASE_VERSION" >> "$GITHUB_OUTPUT"
+          echo "::group::Check project version matches tag"
+          PACKAGE_VERSION="$(grep version pyproject.toml | cut -d'"' -f2)"
+          TAG_VERSION="$(echo "${{ github.ref_name }}" | cut -d'v' -f2)"
+          if [ "$PACKAGE_VERSION" != "$TAG_VERSION" ]; then
+            echo "::error title=Version mismatch::Package version ($PACKAGE_VERSION) does not match tag version ($TAG_VERSION)"
+            exit 1
+          fi
+          echo "version=$PACKAGE_VERSION" >> "$GITHUB_OUTPUT"
+          echo "::endgroup::"
 
   build:
     needs: prepare
@@ -74,7 +71,7 @@ jobs:
           tags: ${{ env.VERSION }} latest
 
       - id: login
-        name: Log in to registry
+        name: Login to registry
         uses: redhat-actions/podman-login@v1
         with:
           registry: ${{ env.REGISTRY }}
@@ -82,7 +79,7 @@ jobs:
           password: ${{ env.REGISTRY_PASS }}
 
       - id: push
-        name: Push to reigstry
+        name: Push image to reigstry
         uses: redhat-actions/push-to-registry@v2
         with:
           registry: ${{ env.REGISTRY }}
